### ISSUE TITLE
413

### ISSUE THREAD

**Issue by dseynaev** [skyscrapers/terraform-awselasticsearch#25]
Hi @duboisph 

I have an almost identical setup to yours
nginx ingress -> gatekeeper auth proxy -> kibana (vpc-based aws elastic)

However, I keep hitting a 413 when trying to access kibana (while the cluster is still completely empty).
Any idea what I could be doing wrong?

**Comment by dseynaev** [comment]
Nvm I solved it, I was missing
```
--enable-authorization-header=false
```
Thank you for making your terraform code public @duboisph, this saved me a day of troubleshooting probably.

**Comment by duboisph** [comment]
Great, glad you figured it out :)
