### ISSUE TITLE
v12 support

### ISSUE THREAD

**Issue by ozhyrenkov** [skyscrapers/terraform-awselasticsearch#28]
Hello!
Thank you so much for the work done so far with this awesome module 👍 
Does this module supports tf 0.12+ ?

**Comment by duboisph** [comment]
Hi @AZhyrenkov , yes these modules are compatible with Terraform 0.12. In fact they will only work with 0.12 or greater. We also succesfully use it with the newest terraform 0.13.

FYI minimum supported version is specified: https://github.com/skyscrapers/terraform-awselasticsearch/blob/master/elasticsearch/versions.tf#L2

**Comment by ozhyrenkov** [comment]
Thank you so much for the quick response, it's a good news :)

**Comment by iuriaranda** [comment]
Considering that your initial question has been answered, I'll close this issue. Feel free to reopen it or open a new one if you still have questions or problems with the module.
